[package]
org = "xlibb"
name = "serdes"
version = "0.2.1"
distribution = "2201.4.0"

[[platform.java11.dependency]]
path = "../native/build/libs/serdes-native-0.2.1-SNAPSHOT.jar"
groupId = "io.xlibb"
artifactId = "serdes-native"
version = "0.2.1"

[[platform.java11.dependency]]
path = "./lib/protobuf-java-3.21.7.jar"
groupId = "com.google.protobuf"
artifactId = "protobuf-java"
version = "3.21.7"

[[platform.java11.dependency]]
path = "./lib/protobuf-java-util-3.21.7.jar"
groupId = "com.google.protobuf"
artifactId = "protobuf-java-util"
version = "3.21.7"
